require File.expand_path('../boot', __FILE__)

# Ruby 2.6 + Rails 6.0 compatibility: ActiveSupport tries to mix into the
# Logger class before it's autoloaded. Pre-requiring fixes the boot.
require 'logger'

require 'rails/all'

# If you have a Gemfile, require the gems listed there, including any gems
# you've limited to :test, :development, or :production.
Bundler.require(:default, Rails.env) if defined?(Bundler)

module AlteredBeast
  class Application < Rails::Application

    # Use the modern (7.1+) cache serialization format. Pre-7.0 default of
    # `6.1` is deprecated and removed in Rails 7.2; setting explicitly to
    # `7.1` silences the warning and is forward-compatible. We don't use
    # `Rails.cache` for anything important, so cache-invalidation isn't a
    # concern.
    config.active_support.cache_format_version = 7.1

    # NOTE: `config.load_defaults 7.1` is intentionally NOT set here. Doing
    # so cascades 7.1 default changes through dozens of subtle behaviors
    # (cookie format, content_type formatting, session serialization,
    # `attr_readonly` strictness, etc.) that the legacy test scaffolding —
    # `rspec_on_rails_on_crack.rb`, `model_stubbing` shim, `have_tag`
    # matcher — was written against pre-7.0 semantics. Opting in requires
    # a coordinated rewrite of those specs in idiomatic RSpec 3. Listed in
    # Plan.md Phase 5.4 polish — keep deferred for now.

    config.assets.enabled = true
    # Version of your assets, change this if you want to expire all your assets
    config.assets.version = '1.0'

    # Settings in config/environments/* take precedence over those specified here.
    # Application configuration should go into files in config/initializers
    # -- all .rb files in that directory are automatically loaded.

    # Put `lib/` on $LOAD_PATH so old-style `require 'node'`,
    # `require 'authentication/by_password'`, etc. resolve. Do NOT use
    # `config.autoload_paths += %W(#{config.root}/lib)` — Zeitwerk would
    # index every file under lib/ and expect its constants to match its
    # filenames, which they don't (e.g. `lib/node.rb` defines `XHTML`).
    $LOAD_PATH.unshift(Rails.root.join('lib').to_s)

    # Only load the plugins named here, in the order given (default is alphabetical).
    # :all can be used as a placeholder for all plugins not explicitly named.
    # config.plugins = [ :exception_notification, :ssl_requirement, :all ]

    # Activate observers that should always be running.
    # config.active_record.observers = :cacher, :garbage_collector, :forum_observer

    # Set Time.zone default to the specified zone and make Active Record auto-convert to this zone.
    # Run "rake -D time" for a list of tasks for finding time zone names. Default is UTC.
    # config.time_zone = 'Central Time (US & Canada)'
    config.active_record.default_timezone = :utc

    # The default locale is :en and all translations from config/locales/*.rb,yml are auto loaded.
    # config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}').to_s]
    # config.i18n.default_locale = :de

    # JavaScript files you want as :defaults (application.js is always included).
    # config.action_view.javascript_expansions[:defaults] = %w(jquery rails)

    # Configure the default encoding used in templates for Ruby 1.9.
    config.encoding = "utf-8"

    # Configure sensitive parameters which will be filtered from the log file.
    config.filter_parameters += [:password]

    # Cookie session signing key. Three sources, in priority order:
    #   1. SECRET_KEY_BASE env var (preferred for production)
    #   2. A `secret` file at the repo root (generated by
    #      `bundle exec rake app:secret_key_base` — itself wired into
    #      `app:bootstrap`)
    #   3. Otherwise: leave unset and let Rails 8's own
    #      "Missing `secret_key_base` for '#{Rails.env}'" guard fire.
    # The file is gitignored. Deleting it invalidates all existing
    # signed cookies; users will silently get fresh sessions.
    secret_file = Rails.root.join('secret')
    if ENV['SECRET_KEY_BASE'].present?
      config.secret_key_base = ENV['SECRET_KEY_BASE']
    elsif File.exist?(secret_file)
      config.secret_key_base = File.read(secret_file).strip
    end
  end
end
